### ISSUE TITLE
Frontend Development

### ISSUE THREAD

**Issue by bhrayhaw** [bhrayhaw/musicplug#3]
- [x] #3 Implement HTML Structure. @gideonagyage 
- [x] #3 Code HTML for Homepage. @gideonagyage 
- [x] #3 Code HTML for About Us page. @gideonagyage 
- [ ] #3 Code HTML for Blog Posts page. @WilliamAdjeiJr 
- [ ] #3 Apply Styling with CSS @perpetualofosu 
- [ ] #3 Write CSS for the Homepage. @perpetualofosu 
- [ ] #3 Write CSS for the About Us page. @bhrayhaw 
- [ ] #3 Write CSS for the Blog Posts page. @bhrayhaw 
- [ ] #3 Enhance Interactivity with JavaScript @WilliamAdjeiJr 
- [ ] #3 Implement dynamic content loading for blog posts. @AngelKafui4 
- [ ] #3 Create interactive navigation menu. @gyamfi32 
- [ ] #3 Add responsive design features for mobile compatibility. @gyamfi32

**Comment by gideonagyage** [comment]
- [x] #3 HTML Pages Created
