### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by bhrayhaw** [bhrayhaw/musicplug#4]
- [ ] #4   Design Website Layout @bhrayhaw 
- [ ] #4  Create wireframes for Homepage, About Us, and Blog Posts pages. @WilliamAdjeiJr 
- [ ] #4  Develop a consistent color scheme and font style guide. @WilliamAdjeiJr 
- [ ] #4 Design navigation menu and footer for site-wide use. @perpetualofosu 
- [ ] #4 Design Content Structure. @perpetualofosu 
- [ ] #4 Outline content sections for each page. @bhrayhaw 
- [ ] #4 Plan layout for blog post entries, including text and image placements. @TimBlakk
