### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by bhrayhaw** [bhrayhaw/musicplug#5]
- [x] #5 Set Up Development Environment @gyamfi32 
- [x] #5 Create GitHub repository for version control. @gyamfi32 
- [x] #5 Set up Replit project and link it to the GitHub repository. @gideonagyage 
- [x] #5 Establish folder structure for project (HTML, CSS, JS, assets). @perpetualofosu 
- [ ] #5 Define Project Resources @WilliamAdjeiJr 
- [ ] #5 Compile a list of free assets and resources. @gideonagyage 
- [ ] #5 Set up access to vector and illustration resources. @gideonagyage
